name: Build Resume

on:
  push:
    branches:
      - main
    paths:
      - "resume.typ"
      - "profile.png"
      - "template.typ"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: typst-community/setup-typst@v3
        with: 
          cache: true

      - run: typst compile --font-path fonts resume.typ resume.pdf

      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: resume.pdf
          target: /var/www/resume/